/** @format */

// Redirects for URLs published by the previous WordPress site.
//
// These paths are still in Google's index, so each one must land on the current
// page that actually answers it. Sending a question-intent article to a generic
// commercial hub reads as a soft 404: the old ranking signal is discarded and
// the destination gains nothing. Targets are chosen by reading the destination
// page, not by slug similarity.
//
// See redirects/README.md for how to append entries from a Search Console
// "Pages" export. Paths carry no trailing slash: the site runs Next's default
// trailingSlash:false, which already strips one before these rules are matched.

export interface LegacyRedirect {
  /** Path as published by the old site, without a trailing slash. */
  from: string;
  /** Current canonical path. Must return 200 and appear in the sitemap. */
  to: string;
  permanent: true;
}

export const legacyRedirects: LegacyRedirect[] = [
  { from: "/vancouver-math-tutor", to: "/", permanent: true },
  { from: "/why-drshreyankeducare-tutoring", to: "/about", permanent: true },
  { from: "/our-tutors", to: "/about", permanent: true },
  { from: "/our-tutoring-process", to: "/about", permanent: true },
  { from: "/unlock-your-child-s-potential-with-personalized-tutoring-from-dr-shreyan-kedu-care", to: "/about", permanent: true },
  { from: "/unlock-your-child-s-potential-with-dr-shreyan-kedu-care-personalized-tutoring-that-makes-a-difference", to: "/about", permanent: true },
  { from: "/tutors-in-burnaby", to: "/math-tutor-burnaby", permanent: true },
  { from: "/tutors-in-vancouver-how-to-find-and-become-the-best-with-dr-shreyank-educare", to: "/math-tutor-vancouver", permanent: true },
  { from: "/our-services", to: "/services", permanent: true },
  { from: "/in-person-tutoring", to: "/services", permanent: true },
  { from: "/online-tutoring", to: "/services", permanent: true },
  { from: "/final-exam-review-courses", to: "/services", permanent: true },
  { from: "/summer-tutoring-courses", to: "/services", permanent: true },
  { from: "/how-to-find-the-best-math-tutor-in-canada", to: "/guides/how-to-choose-a-tutor-burnaby-vancouver", permanent: true },
  { from: "/understanding-how-online-math-tutoring-platforms-work", to: "/services", permanent: true },
  { from: "/online-math-tutor-bc", to: "/services", permanent: true },
  { from: "/how-summer-tutoring-courses-in-north-vancouver-help-students-stay-ahead-academically", to: "/math-tutor-vancouver", permanent: true },
  { from: "/how-to-find-the-right-in-home-tutoring-services-in-north-vancouver-for-your-childs-learning-needs", to: "/math-tutor-vancouver", permanent: true },
  { from: "/best-math-tutor-in-canada-2025", to: "/services", permanent: true },
  { from: "/best-math-tutor-in-canada-online-in-person-math-tutoring-bc", to: "/services", permanent: true },
  { from: "/top-benefits-of-choosing-in-home-tutoring-services-in-north-vancouver-for-your-childs-academic-success", to: "/math-tutor-vancouver", permanent: true },
  { from: "/top-strategies-to-choose-the-right-academic-tutoring-in-north-vancouver-for-your-child", to: "/math-tutor-vancouver", permanent: true },
  { from: "/online-tutoring-for-math", to: "/services", permanent: true },
  { from: "/how-academic-tutoring-in-north-vancouver-can-boost-your-childs-learning-and-confidence", to: "/math-tutor-vancouver", permanent: true },
  { from: "/online-math-tutor-in-canada", to: "/services", permanent: true },
  { from: "/how-to-choose-the-right-tutoring-services-in-north-vancouver-for-your-child", to: "/math-tutor-vancouver", permanent: true },
  { from: "/top-benefits-of-enrolling-in-tutoring-services-in-north-vancouver-for-academic-success", to: "/math-tutor-vancouver", permanent: true },
  { from: "/top-reasons-parents-choose-personalized-tutoring-in-north-vancouver-for-their-childrens-success", to: "/math-tutor-vancouver", permanent: true },
  { from: "/how-personalized-tutoring-in-north-vancouver-helps-students-reach-their-academic-potential", to: "/math-tutor-vancouver", permanent: true },
  { from: "/top-reasons-parents-choose-the-best-tutoring-in-north-vancouver-for-their-children", to: "/math-tutor-vancouver", permanent: true },
  { from: "/how-to-find-the-best-tutoring-in-north-vancouver-for-academic-success", to: "/math-tutor-vancouver", permanent: true },
  { from: "/holiday-tutoring-vancouver-bc", to: "/services", permanent: true },
  { from: "/contact-us", to: "/contact", permanent: true },
  { from: "/new-year-tutoring-offer-in-bc-free-demo-class-start-2026-strong", to: "/contact", permanent: true },
  { from: "/comprehensive-guide-to-online-math-help-resources-for-struggling-students-2", to: "/resources", permanent: true },
  { from: "/tips-for-effective-math-tutoring-sessions", to: "/resources", permanent: true },
  { from: "/tips-for-effective-online-math-tutoring-sessions", to: "/resources", permanent: true },
  { from: "/bc-curriculum-guide", to: "/resources", permanent: true },
  { from: "/role-of-a-math-tutor-guide", to: "/resources", permanent: true },
  { from: "/grade-10-math-exam-guide-free-exam-pack-download", to: "/resources", permanent: true },
  { from: "/math-tutor-near-me-parent-roadmap-2025", to: "/resources", permanent: true },
  { from: "/improve-math-grades-fast-10-tips-for-bc-students", to: "/resources", permanent: true },
  { from: "/how-to-master-grade-10-math-in-bc-a-complete-study-guide-for-students", to: "/resources", permanent: true },
  { from: "/thesis-and-academic-writing", to: "/resources", permanent: true },
  { from: "/math-tutoring", to: "/programs/mathematics", permanent: true },
  { from: "/math-tutor-dr-shreyank-educare", to: "/programs/mathematics", permanent: true },
  { from: "/math-tutoring-burnaby", to: "/math-tutor-burnaby", permanent: true },
  { from: "/vancouver-math-tutors", to: "/programs/vancouver-math-tutoring", permanent: true },
  { from: "/grade-11-functions-graphs-math-tutor-burnaby", to: "/programs/mathematics", permanent: true },
  { from: "/math-tutoring-burnaby-vancouver-online-canada", to: "/math-tutor-burnaby", permanent: true },
  { from: "/radicals-rational-equations-absolute-values-math-tutor", to: "/programs/mathematics", permanent: true },
  { from: "/factoring-algebra-math-tutor-burnaby", to: "/programs/mathematics", permanent: true },
  { from: "/comprehensive-guide-to-math-tutoring-for-elementary-students-online", to: "/programs/mathematics", permanent: true },
  { from: "/mode-in-statistics-high-school", to: "/programs/mathematics", permanent: true },
  { from: "/median-statistics-high-school-canada", to: "/programs/mathematics", permanent: true },
  { from: "/mean-vs-median-vs-mode-bc", to: "/programs/mathematics", permanent: true },
  { from: "/mean-median-mode-help-bc-students", to: "/programs/mathematics", permanent: true },
  { from: "/top-math-concepts-bc-students-struggle-with-how-to-fix-them", to: "/programs/mathematics", permanent: true },
  { from: "/📐-best-math-tutor-in-burnaby-for-high-school-students-grades-6-12", to: "/math-tutor-burnaby", permanent: true },
  { from: "/%f0%9f%93%90-best-math-tutor-in-burnaby-for-high-school-students-grades-6-12", to: "/math-tutor-burnaby", permanent: true },
  { from: "/%F0%9F%93%90-best-math-tutor-in-burnaby-for-high-school-students-grades-6-12", to: "/math-tutor-burnaby", permanent: true },
  { from: "/calculus-tutoring", to: "/programs/pre-calculus", permanent: true },
  { from: "/calculus-tutor-burnaby-tangents-integrals-optimization", to: "/programs/pre-calculus", permanent: true },
  { from: "/essential-pre-cal-12-tutoring-resources", to: "/programs/pre-calculus", permanent: true },
  { from: "/best-resources-for-studying-precalculus-effectively", to: "/programs/pre-calculus", permanent: true },
  { from: "/grade-12-calculus-math-tutor-burnaby-canada", to: "/programs/pre-calculus", permanent: true },
  { from: "/pre-calculus-formulas-tricks-for-bc-students-free-study-sheet", to: "/programs/pre-calculus", permanent: true },
  { from: "/mastering-the-identities-of-trigonometry__simple-guide", to: "/programs/pre-calculus", permanent: true },
  { from: "/why-understanding-the-identities-of-trigonometry-is-essential-for-math-success", to: "/programs/pre-calculus", permanent: true },
  { from: "/calculus-and-vectors-explained", to: "/programs/pre-calculus", permanent: true },
  { from: "/understanding-the-calculus-quotient-rule-step-by-step-guide", to: "/programs/pre-calculus", permanent: true },
  { from: "/precalculus-12-precalc-12-math-12-guide", to: "/programs/pre-calculus", permanent: true },
  { from: "/www-drshreyankeducare-com-pre-calculus-12-tutoring", to: "/programs/pre-calculus", permanent: true },
  { from: "/how-calculus-tutoring-in-burnaby-helps-students-build-confidence-and-improve-grades", to: "/programs/pre-calculus", permanent: true },
  { from: "/top-reasons-to-choose-professional-calculus-tutoring-in-burnaby-for-high-school-and-university-success", to: "/programs/pre-calculus", permanent: true },
  { from: "/ubc-math-100-study-guide-for-first-year-students-tips-from-expert-calculus-tutors", to: "/programs/university-mathematics", permanent: true },
  { from: "/pre-calculus-11-12-math-tutoring-burnaby", to: "/programs/pre-calculus", permanent: true },
  { from: "/pre-calculus-12-exam-prep-bc-2026", to: "/programs/pre-calculus", permanent: true },
  { from: "/chemistry-tutoring", to: "/programs/chemistry", permanent: true },
  { from: "/chemistry-tutoring-burnaby-vancouver", to: "/programs/chemistry", permanent: true },
  { from: "/top-resources-for-mastering-chem-11-2", to: "/programs/chemistry", permanent: true },
  { from: "/how-to-choose-the-best-chemistry-coaching-in-burnaby-for-academic-success", to: "/programs/chemistry", permanent: true },
  { from: "/top-benefits-of-enrolling-in-the-best-chemistry-coaching-in-burnaby-for-high-school-and-college-students", to: "/programs/chemistry", permanent: true },
  { from: "/🔬-best-chemistry-tutoring-in-burnaby-vancouver-ib-ap-bc-curriculum", to: "/programs/chemistry", permanent: true },
  { from: "/%f0%9f%94%ac-best-chemistry-tutoring-in-burnaby-vancouver-ib-ap-bc-curriculum", to: "/programs/chemistry", permanent: true },
  { from: "/%F0%9F%94%AC-best-chemistry-tutoring-in-burnaby-vancouver-ib-ap-bc-curriculum", to: "/programs/chemistry", permanent: true },
  { from: "/physics-tutoring", to: "/programs/physics", permanent: true },
  { from: "/science-physics-tutoring-burnaby", to: "/programs/physics", permanent: true },
  { from: "/hardest-high-school-physics-topics-bc-curriculum", to: "/programs/physics", permanent: true },
  { from: "/the-math-behind-waves-and-sound-burnaby-tutor", to: "/programs/physics", permanent: true },
  { from: "/mastering-waves-and-sound-physics-tutoring-burnaby", to: "/programs/physics", permanent: true },
  { from: "/mastering-projectile-motion-physics-12-bc", to: "/programs/physics", permanent: true },
  { from: "/types-of-physics-tutoring-in-canada-choose-what-suits-you", to: "/programs/physics", permanent: true },
  { from: "/how-calculus-explains-velocity-and-acceleration-in-grade-12-physics", to: "/programs/physics", permanent: true },
  { from: "/calculus-velocity-acceleration-physics-math", to: "/programs/physics", permanent: true },
  { from: "/physics-math-tutoring-high-school-canada", to: "/programs/physics", permanent: true },
  { from: "/algebra-trigonometry-for-physics", to: "/programs/physics", permanent: true },
  { from: "/physics-problems-math-skills-tutor-canada", to: "/programs/physics", permanent: true },
  { from: "/newtons-laws-of-motion-high-school-physics", to: "/programs/physics", permanent: true },
  { from: "/kinematics-in-high-school-physics", to: "/programs/physics", permanent: true },
  { from: "/electricity-circuits-explained", to: "/programs/physics", permanent: true },
  { from: "/work-energy-power-in-high-school-physics", to: "/programs/physics", permanent: true },
  { from: "/physics-tutor-brentwood-burnaby", to: "/math-tutor-burnaby", permanent: true },
  { from: "/math-physics-tutor-metrotown-burnaby", to: "/math-tutor-burnaby", permanent: true },
  { from: "/private-physics-tutor-burnaby", to: "/math-tutor-burnaby", permanent: true },
  { from: "/why-you-need-a-vancouver-physics-tutor", to: "/math-tutor-vancouver", permanent: true },
  { from: "/top-reasons-students-prefer-the-best-physics-coaching-in-burnaby-for-competitive-exams-and-school-support", to: "/programs/physics", permanent: true },
  { from: "/how-to-choose-the-best-physics-coaching-in-burnaby-for-academic-success", to: "/programs/physics", permanent: true },
  { from: "/www-drshreyankeducare-com-peo-statics-dynamics-exam-tutoring", to: "/programs/university-physics", permanent: true },
  { from: "/biology-tutoring", to: "/programs/biology", permanent: true },
  { from: "/dna-replication-fork-diagram-guide", to: "/programs/biology", permanent: true },
  { from: "/why-dna-replication-is-semiconservative", to: "/programs/biology", permanent: true },
  { from: "/computer-science-tutoring", to: "/programs/computer-science", permanent: true },
  { from: "/why-learn-programming-boost-skills-career-2026", to: "/programs/computer-science", permanent: true },
  { from: "/how-to-choose-the-best-computer-science-tutoring-coaching-in-burnaby-top-qualities-and-local-options", to: "/programs/computer-science", permanent: true },
  { from: "/top-computer-science-tutoring-coaching-services-in-burnaby-what-to-look-for-who-stands-out", to: "/programs/computer-science", permanent: true },
  { from: "/how-to-choose-the-right-computer-science-tutoring-in-burnaby-for-your-learning-goals", to: "/programs/computer-science", permanent: true },
  { from: "/top-benefits-of-personalized-computer-science-tutoring-in-burnaby-for-high-school-and-college-students", to: "/programs/computer-science", permanent: true },
  { from: "/python", to: "/programs/python", permanent: true },
  { from: "/java", to: "/programs/computer-science", permanent: true },
  { from: "/web-development", to: "/programs/web-development", permanent: true },
  { from: "/programs/language-programs", to: "/programs", permanent: true },
  { from: "/programs/test-prep-burnaby", to: "/programs", permanent: true },
  { from: "/college-entrance-exam-prep-canadian-students-2026", to: "/programs", permanent: true },
  { from: "/best-test-prep-courses-2025-comparison", to: "/programs", permanent: true },
  { from: "/math-physics-chemistry-tutoring-drshreyank-educare", to: "/programs", permanent: true },
  { from: "/top-10-reasons-why-the-best-science-coaching-in-burnaby-is-the-right-choice-for-academic-success", to: "/programs", permanent: true },
  { from: "/top-10-benefits-of-joining-the-best-science-coaching-in-burnaby-for-students", to: "/programs", permanent: true },
  { from: "/science-tutoring", to: "/programs", permanent: true },
  { from: "/finance-tutoring", to: "/programs/finance", permanent: true },
  { from: "/how-to-choose-the-right-finance-tutor-in-burnaby-for-your-learning-goals", to: "/programs/finance", permanent: true },
  { from: "/top-reasons-to-hire-a-professional-finance-tutor-in-burnaby-for-academic-success", to: "/programs/finance", permanent: true },
  { from: "/ib-math-tutoring-from-grade-6-to-grade-12", to: "/programs/ib-ap-tutoring", permanent: true },
  { from: "/mastering-calculus-12-ap-prep-burnaby-bc", to: "/programs/ib-ap-tutoring", permanent: true },
  { from: "/why-bc-students-need-structured-math-support", to: "/blog/importance-of-high-school-mathematics", permanent: true },
  { from: "/blog/physics-high-school-physics", to: "/physics-12-tutor-burnaby", permanent: true },
  { from: "/blog/physics-tutoring-high-school-physics", to: "/physics-12-tutor-burnaby", permanent: true },
  { from: "/blog/physics-tutoring-university-physics", to: "/programs/university-physics", permanent: true },
  { from: "/blog/physics-university-level-physics", to: "/programs/university-physics", permanent: true },
  { from: "/blog/physics-tutoring-physics-concepts-problem-solving", to: "/physics-problem-solving-tutor", permanent: true },
  { from: "/blog/mathematics-pre-calculus", to: "/pre-calculus-12-tutor-burnaby", permanent: true },
  { from: "/blog/burnaby-stem-tutoring-physics-11-12", to: "/physics-12-tutor-burnaby", permanent: true },
  { from: "/blog/burnaby-stem-tutoring-chemistry-11-12", to: "/chemistry-12-tutor-burnaby", permanent: true },
  { from: "/blog/burnaby-stem-tutoring-biology-11-12", to: "/biology-12-tutor-burnaby", permanent: true },
  { from: "/blog/burnaby-stem-tutoring-mathematics-grades-8-12", to: "/math-tutor-burnaby", permanent: true },
  { from: "/blog/burnaby-stem-tutoring-computer-science-programming", to: "/programs/computer-science", permanent: true },
  { from: "/blog/burnaby-stem-tutoring-statistics-data-analysis", to: "/programs/university-mathematics", permanent: true },
  { from: "/how-to-solve-differential-equations", to: "/programs/university-mathematics", permanent: true },
  { from: "/how-to-choose-the-right-math-tutor-in-burnaby-a-parents-complete-guide", to: "/guides/how-to-choose-a-tutor-burnaby-vancouver", permanent: true },
  { from: "/top-benefits-of-hiring-a-math-tutor-in-burnaby-to-boost-your-childs-academic-success", to: "/services", permanent: true },
  { from: "/real-life-applications-of-math", to: "/blog", permanent: true },
  { from: "/how-to-choose-the-right-tutor-in-burnaby-a-parents-guide-to-academic-excellence", to: "/guides/how-to-choose-a-tutor-burnaby-vancouver", permanent: true },
  { from: "/tutoring-young-leaeners", to: "/services", permanent: true },
  { from: "/ib-tutoring-vancouver", to: "/programs/ib-ap-tutoring", permanent: true },
  { from: "/personalized-tutoring-in-burnaby-north-vancouver-coquitlam-the-key-to-academic-success", to: "/math-tutor-burnaby", permanent: true },
  { from: "/french-tutor-in-north-vancouver", to: "/programs/french", permanent: true },
  { from: "/top-5-benefits-of-hiring-a-local-tutor-in-burnaby-for-your-childs-academic-success", to: "/services", permanent: true },
  { from: "/second-law-on-inclined-plane-with-friction", to: "/programs/physics", permanent: true },
  { from: "/problems-in-math-for-high-school-students", to: "/programs/mathematics", permanent: true },
  { from: "/is-canada-losing-its-education-edge", to: "/blog", permanent: true },
  { from: "/how-to-manage-exam-stress-student-wellness-tips", to: "/resources", permanent: true },
  { from: "/top-study-tips-for-high-school-student", to: "/resources", permanent: true },
  { from: "/how-to-choose-the-right-tutor-for-your-child", to: "/guides/how-to-choose-a-tutor-burnaby-vancouver", permanent: true },
  { from: "/struggling-with-math", to: "/programs/mathematics", permanent: true },
  { from: "/frequently-asked-questions", to: "/about", permanent: true },
  { from: "/demo-videos", to: "/resources", permanent: true },
  { from: "/practice-materials", to: "/resources", permanent: true },
  { from: "/blog/page", to: "/blog", permanent: true },
  { from: "/free-assessment", to: "/book", permanent: true },
  { from: "/book-a-free-assessment", to: "/book", permanent: true },
  { from: "/category/biology", to: "/programs/biology", permanent: true },
  { from: "/category/blog", to: "/blog", permanent: true },
  { from: "/category/calculus-2", to: "/programs/pre-calculus", permanent: true },
  { from: "/category/maths/calculus", to: "/programs/pre-calculus", permanent: true },
  { from: "/category/chemistry", to: "/programs/chemistry", permanent: true },
  { from: "/category/computer-science", to: "/programs/computer-science", permanent: true },
  { from: "/category/exams", to: "/programs", permanent: true },
  { from: "/category/finance", to: "/programs/finance", permanent: true },
  { from: "/category/maths", to: "/programs/mathematics", permanent: true },
  { from: "/category/physics", to: "/programs/physics", permanent: true },
  { from: "/category/stem", to: "/programs/burnaby-stem-tutoring", permanent: true },
  { from: "/category/stem/stem-education", to: "/programs/burnaby-stem-tutoring", permanent: true },
  { from: "/category/stem-education-2", to: "/programs/burnaby-stem-tutoring", permanent: true },
  { from: "/category/tutor", to: "/services", permanent: true },
  { from: "/category/uncategorized", to: "/blog", permanent: true },
];
