/**
 * Generates content/own-form-routes.ts: every route that renders its own
 * enquiry form, so the shared footer form can stand down there.
 *
 * Generated rather than hand-listed because the source of truth is the page
 * data, and a list that drifts would put two competing forms back on a page.
 * Strings only: the Footer is a client component, so importing the full page
 * data would ship it to the browser.
 *
 * Run: npm run seo:own-form-routes
 */
import { readdirSync, existsSync, writeFileSync } from "node:fs";

const { cities, cityPath } = await import("../data/cities.ts");
const { seoPages, seoPagePath } = await import("../data/seoPages.ts");
const { verticalPages, verticalPath } = await import("../data/verticalPages.ts");
const { redirectSources } = await import("../data/redirects.ts");
const { retiredPaths } = await import("../content/page-policy.ts");

const programs = readdirSync("app/programs")
  .filter((d) => existsSync(`app/programs/${d}/page.tsx`))
  .map((slug) => `/programs/${slug}`);

const live = (path: string) => !redirectSources.has(path) && !retiredPaths.has(path);

// Pages that render their own form directly rather than through a template.
const STANDALONE = ["/", "/book"];

const routes = [
  ...STANDALONE,
  ...programs,
  ...cities.map((c) => cityPath(c.slug)),
  ...verticalPages.map((p) => verticalPath(p.slug)),
  ...seoPages.map((p) => seoPagePath(p.slug)),
]
  .filter(live)
  .sort();

const unique = [...new Set(routes)];

writeFileSync(
  "content/own-form-routes.ts",
  `/** @format */\n\n` +
    `// GENERATED by scripts/build-own-form-routes.mts — do not edit by hand.\n` +
    `// Routes that render their own enquiry form, where the shared footer form\n` +
    `// must not also appear. Regenerate with \`npm run seo:own-form-routes\`.\n\n` +
    `export const ROUTES_WITH_THEIR_OWN_FORM: ReadonlySet<string> = new Set([\n` +
    unique.map((r) => `  ${JSON.stringify(r)},`).join("\n") +
    `\n]);\n`,
  "utf8",
);

console.log(`wrote content/own-form-routes.ts`);
console.log(`  standalone: ${STANDALONE.length}`);
console.log(`  programs:  ${programs.length}`);
console.log(`  cities:    ${cities.length}`);
console.log(`  verticals: ${verticalPages.length}`);
console.log(`  seoPages:  ${seoPages.length}`);
console.log(`  total live routes: ${unique.length}`);
